name: SWA Deploy (clean)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Avoid overlapping deploys
concurrency:
  group: swa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # (Optional) quick visibility into what’s being built
      - name: Show project layout
        run: |
          echo "=== root ==="; ls -la
          echo "=== src ==="; ls -la src || true
          echo "=== index.html head ==="; sed -n '1,120p' index.html || true

      - name: Build & Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Required: set this secret in GitHub → Settings → Secrets → Actions
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          # Paths for your project (adjust only if your structure is different)
          app_location: "/"          # repo root (where index.html, package.json live)
          api_location: "api"        # Azure Functions folder (omit if you have none)
          output_location: "dist"    # Vite build output
          # Explicit build command so Oryx runs Vite
          app_build_command: "npm ci && npm run build"
