name: SWA Deploy (self-build app, build API)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: swa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build (Vite -> dist/)
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          # Frontend (we already built)
          app_location: "/"
          app_artifact_location: "dist"
          skip_app_build: true
          # API (let the action detect/package it)
          api_location: "api"
          # Push minimal app settings so Azure knows it's Node (no portal needed)
          app_settings_json: |
            {
              "FUNCTIONS_WORKER_RUNTIME": "node"
            }
