name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: swa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (Vite -> dist/)
        run: npm run build

      - name: Verify dist (fail if wrong)
        run: |
          echo "=== dist ==="; ls -la dist
          echo "=== dist/assets ==="; ls -la dist/assets
          echo "=== HEAD of dist/index.html ==="; sed -n '1,120p' dist/index.html
          if grep -q "src/main.tsx" dist/index.html; then
            echo "ERROR: dist/index.html still references src/main.tsx (build not applied)"; exit 1;
          fi
          if grep -q 'src="/assets/' dist/index.html; then
            echo "ERROR: dist/index.html uses absolute /assets paths. Set base: \"./\" in vite.config.ts"; exit 1;
          fi

      # IMPORTANT: point app_location to dist and upload THAT folder as-is
      - name: Deploy to Azure Static Web Apps (upload dist as app)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "dist"          # << serve the built app directly
          app_artifact_location: ""     # << nothing else to look for
          skip_app_build: true          # we already built
          api_location: "api"
