name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: swa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout (debug)
        run: |
          echo "=== ls -la (root) ==="; ls -la
          echo "=== ls -la src (if exists) ==="; ls -la src || true
          echo "=== ls -la api (if exists) ==="; ls -la api || true
          echo "=== print root index.html head (if exists) ==="; sed -n '1,80p' index.html || true
          echo "=== print vite.config.ts (if exists) ==="; sed -n '1,120p' vite.config.ts || true

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"; npm ci
          else
            echo "No lockfile, using npm install"; npm install
          fi

      - name: Build (Vite -> dist/)
        run: npm run build

      - name: Verify build (debug)
        run: |
          echo "=== dist ==="; ls -la dist || true
          echo "=== dist/index.html head ==="; sed -n '1,80p' dist/index.html || true

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"            
          app_artifact_location: "dist"  
          api_location: "api"          
          skip_app_build: true
